name: Tenuto .NET6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/josephmyers/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Print
      run: echo ${{ steps.gitversion.outputs.AssemblySemVer }}
#    - name: Pack
 #     run: dotnet pack -c Release /p:PackageVersion=${{steps.gitversion.outputs.AssemblySemVer}}
  #  - name: Push to GitHub
   #   run: dotnet nuget push "bin/Release/*.nupkg" -k ${NUGET_AUTH_TOKEN}
    #- name: Push to Nuget
     # run: dotnet nuget push "bin/Release/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_ORG}}
