name: Tenuto .NET6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/josephmyers/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.PAT}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack -c Release
    - name: Push Package
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
